package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

// Artwork returns ArtworkResolver implementation.
func (r *Resolver) Artwork() ArtworkResolver { return &artworkResolver{r} }

// Chapter returns ChapterResolver implementation.
func (r *Resolver) Chapter() ChapterResolver { return &chapterResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type artworkResolver struct{ *Resolver }
type chapterResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
