// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Artwork struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	Summary       string     `json:"summary"`
	Cover         string     `json:"cover"`
	Author        *User      `json:"author"`
	Status        Status     `json:"status"`
	ArtType       ArtType    `json:"artType"`
	LatestChapter int32      `json:"latestChapter"`
	Chapters      []*Chapter `json:"chapters"`
	CreatedAt     string     `json:"createdAt"`
	UpdatedAt     string     `json:"updatedAt"`
	Genres        []*Genre   `json:"genres"`
	Meta          *string    `json:"meta,omitempty"`
}

type Chapter struct {
	ID         string   `json:"id"`
	Title      string   `json:"title"`
	Artwork    *Artwork `json:"artwork"`
	Gallery    []string `json:"gallery"`
	Content    *string  `json:"content,omitempty"`
	ChapterNum int32    `json:"chapterNum"`
	CreatedAt  string   `json:"createdAt"`
	UpdatedAt  string   `json:"updatedAt"`
	Meta       *string  `json:"meta,omitempty"`
}

type Genre struct {
	ID    string `json:"id"`
	Genre string `json:"genre"`
}

type Query struct {
}

type User struct {
	ID        string     `json:"id"`
	FirstName string     `json:"firstName"`
	LastName  string     `json:"lastName"`
	Username  string     `json:"username"`
	Email     string     `json:"email"`
	Role      Role       `json:"role"`
	Bio       string     `json:"bio"`
	ImageURI  string     `json:"imageUri"`
	CreatedAt string     `json:"createdAt"`
	Artworks  []*Artwork `json:"artworks"`
}

type ArtType string

const (
	ArtTypeNovel ArtType = "NOVEL"
	ArtTypeManga ArtType = "MANGA"
)

var AllArtType = []ArtType{
	ArtTypeNovel,
	ArtTypeManga,
}

func (e ArtType) IsValid() bool {
	switch e {
	case ArtTypeNovel, ArtTypeManga:
		return true
	}
	return false
}

func (e ArtType) String() string {
	return string(e)
}

func (e *ArtType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ArtType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ArtType", str)
	}
	return nil
}

func (e ArtType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ArtType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ArtType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleReader Role = "READER"
	RoleArtist Role = "ARTIST"
)

var AllRole = []Role{
	RoleReader,
	RoleArtist,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleReader, RoleArtist:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Status string

const (
	StatusOngoing   Status = "ONGOING"
	StatusCompleted Status = "COMPLETED"
)

var AllStatus = []Status{
	StatusOngoing,
	StatusCompleted,
}

func (e Status) IsValid() bool {
	switch e {
	case StatusOngoing, StatusCompleted:
		return true
	}
	return false
}

func (e Status) String() string {
	return string(e)
}

func (e *Status) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Status(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

func (e Status) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Status) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Status) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
